### ISSUE TITLE
成都中医药大学地图路径混乱

### ISSUE THREAD

**Issue by yanyaoli** [fabulous-man/run_for_you#1]
![7c1e6ff657f67595ce0572123cd9b39](https://github.com/fabulous-man/run_for_you/assets/120553430/359f8299-dd04-4808-9f85-d9ebbaa51ff4)

**Comment by fabulous-man** [comment]
问题原因：当时是直接将路网线导入，没有考虑到线与线的连续性的问题

解决办法：1.根据图论建立哈密顿回路
2.今晚我会将路线图重新上传。
